spring.application.name=embeddedAI
logging.level.org.springframework=DEBUG
spring.security.user.name=ngp-admin
spring.security.user.password=subex@123
spring.main.allow-bean-definition-overriding=true

##spring.ai.openai.apikey=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
#spring.ai.openai.apikey=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
#spring.ai.openai.base-url=https://api.groq.com/openai
#spring.ai.openai.chat.options.model=llama3-70b-8192
#spring.ai.openai.chat.options.temperature=0.7
##spring.ai.openai.embedding.options.model=text-embedding-ada-002

## Spring AI Neo4j Vector Store Configurations
#spring.ai.vectorstore.neo4j.initialize-schema=true
#spring.ai.vectorstore.neo4j.database-name=neo4j
#spring.ai.vectorstore.neo4j.index-name=custom-index
#spring.ai.vectorstore.neo4j.dimensions=1536
#spring.ai.vectorstore.neo4j.distance-type=cosine
#
#spring.neo4j.uri=neo4j://localhost:7687
#spring.neo4j.authentication.username=neo4j
#spring.neo4j.authentication.password=your_password
#
#
#spring.ai.postgresml.embedding.options.transformer=distilbert-base-uncased
#spring.ai.postgresml.embedding.options.vectorType=PG_ARRAY
#spring.ai.postgresml.embedding.options.metadataMode=EMBED
#spring.ai.postgresml.embedding.options.kwargs.device=cpu
#
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.ai.vectorstore.pgvector.index-type=HNSW
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#spring.ai.vectorstore.pgvector.dimensions=1536
#spring.ai.vectorstore.pgvector.batching-strategy=TOKEN_COUNT
#spring.ai.vectorstore.pgvector.max-document-batch-size=10000

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral
#mistral
spring.ai.ollama.chat.options.temperature=0.7


spring.data.redis.uri=redis://localhost:6379
spring.ai.vectorstore.redis.initialize-schema=true
spring.ai.vectorstore.redis.index-name=custom-index
spring.ai.vectorstore.redis.prefix=custom-prefix
spring.ai.vectorstore.redis.batching-strategy=TOKEN_COUNT
#spring.ai.embedding-service.url=http://localhost:11434/api/embed
#spring.redis.host=localhost
#spring.redis.port=11434


